spring:
  application:
    name:talon-ai
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: llama3.2:3b
    openai:
      base-url: https://dashscope.aliyuncs.com/compatible-mode
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: qwen-max-latest
logging:
  level:
    org.springframework.ai.chat.client.advisor: DEBUG
    com.example.ai: DEBUG
